### ISSUE TITLE
Extend Spack module checks on BB5

### ISSUE THREAD

**Issue by pafonta** [BlueBrain/atlas-alignment#31]
## Goal

Maybe, separate the logic for inference and the logic for training logic so that people could use `atlalign` only for **inference** without the need to install the dependencies for **training** (e.g. `LPIPS-TensorFlow`). Especially when such dependency is not on PyPI, like `LPIPS-TensorFlow`.

## Context

We have learned that to check a Spack module we could just do `import atlalign` on BB5.

An extended check could be to run `pytest tests/test_nn.py` on BB5.

However, that's tricky at the moment. Indeed, there are two hardcoded errors at the module level when the package `LPIPS-TensorFlow` is not installed (see next section below). The two concerned modules are: `atlalign.ml_utils.losses` and `atlalign.metrics`.

With the current architecture of `atlalign`, there is no way to go around the hardcoded errors for `LPIPS-TensorFlow` without deleting the errors in the two modules. That's because a) the module `atlalign.ml_utils.losses` is imported in `ml_utils/__init__.py` and b) the module `atlalign.ml_utils` is imported in the core modules: `atlalign.nn` and `atlalign.ml_utils.models`.

🚫 So, trying to use `atlalign` just for **inference** ends up trying to load the package `LPIPS-TensorFlow`, even if `LPIPS-TensorFlow` is only used for **training**.

## References

The two hardcoded errors when `LPIPS-TensorFlow` is not installed:

https://github.com/BlueBrain/atlas_alignment/blob/d01ff4bc3645699d10a52acf25b5cc694dd1da65/atlalign/ml_utils/losses.py#L25-L35

https://github.com/BlueBrain/atlas_alignment/blob/d01ff4bc3645699d10a52acf25b5cc694dd1da65/atlalign/metrics.py#L41-L51

**Comment by Stannislav** [comment]
Maybe the easiest would be do remove all imports of `atlalign.ml_utils.losses` from ?

@jankrepl do you think it would break a lot of things?

I see there's a number of module-scoped loss-related variables defined in `atlalign.ml_utils.__init__`, probably these could be moved one level down to `atlalign.ml_utils.losses` as well.

**Comment by jankrepl** [comment]
@Stannislav 
I think the easiest fix is to literally move imports of `lpips-tf` inside of the functions that are using them. There are 2 functions that use it in 2 different modules.

https://github.com/BlueBrain/atlas_alignment/blob/master/atlalign/ml_utils/losses.py#L151-L163

https://github.com/BlueBrain/atlas_alignment/blob/master/atlalign/metrics.py#L969-L1014


After doing this, there will probably be a couple of tests failing, however, we can mark them in some way and skip them on `BB5`.


Other that this quick fix, we can totally reorganize imports/modules in some more meaningful way:)

**Comment by Stannislav** [comment]
Yes, that's definitely a solution too.

**Comment by pafonta** [comment]
Hello @Stannislav,

> Maybe the easiest would be do remove all imports of `atlalign.ml_utils.losses` from ?
>
> I see there's a number of module-scoped loss-related variables defined in `atlalign.ml_utils.__init__` (`ALL_IMAGE_LOSSES`, `ALL_DVF_LOSSES`, etc.), probably these could be moved one level down to `atlalign.ml_utils.losses` as well.
> 
> @pafonta would that solve the issue or is there maybe something else?

That would `not` solve the issue.

Indeed, `tests/test_nn.py` imports `atlalign.nn` and `atlalign.nn` imports losses from `atlalign.ml_utils.losses`. Any import from `atlalign.ml_utils.losses` will execute the following part which makes the execution stop:

https://github.com/BlueBrain/atlas_alignment/blob/d01ff4bc3645699d10a52acf25b5cc694dd1da65/atlalign/ml_utils/losses.py#L25-L35

One could see it by doing:

```
git clone https://github.com/BlueBrain/atlas-alignment

# Remove as suggested the imports from atlalign.ml_utils.losses in atlalign/ml_utils/__init__.py.
cp /dev/null atlalign/ml_utils/__init__.py

pip install .

# This stops with the `ModuleNotFoundError` exception.
python -c 'from atlalign.ml_utils.losses import psnr'
```

**Comment by Stannislav** [comment]
Ah yes, I just assumed you don't need to import from the `losses` module at all for inference. Seems like you do.

Then suggestion by @jankrepl ?
